### ISSUE TITLE
--mathjax requires argument

### ISSUE THREAD

**Issue by deltakam** [vim-pandoc/vim-pandoc#190]
When I do `Pandoc html --mathjax`, I get the following error. It was fine a few months ago, but it does not work recently.

---

Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kwang-sungjun/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 204, in **call**
    c_opts, c_args = getopt.gnu_getopt(shlex.split(args), self.opts.shortopts, self.opts.longopts)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 131, in gnu_getopt
    opts, args = do_longs(opts, args[0][2:], longopts, args[1:])
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 156, in do_longs
    raise GetoptError('option --%s requires argument' % opt, opt)
getopt.GetoptError: option --mathjax requires argument     

---

I am using MacVim. Could it be some issue from an updated getopt?

**Comment by fmoralesc** [comment]
No, it's that `--mathjax`can take an optional argument and the parser
doesn't handle that properly. Will see what I can do.

**Comment by deltakam** [comment]
Thanks. Meanwhile, if there is a workaround, please let me know.

**Comment by fmoralesc** [comment]
It seems like getopt can't handle optional arguments for long options, so
the solution will have to be to move to argparse (or other library) or to
parse it by hand...

**Comment by fmoralesc** [comment]
I just pushed some changes that should handle this.

**Comment by deltakam** [comment]
Amazing. I checked that it works!

**Comment by mortang2410** [comment]
It seems to be broken again. The check for mathjax is no longer in the source. Maybe if someone else can confirm it, the bug should be reopened.

**Comment by PandaScience** [comment]
I can confirm that this is still an issue. You can check what the plugin is doing via `:messages` in vim, e.g. for 
`:Pandoc! --template=GitHub.html5 --mathjax` 
it logs
`vim-pandoc: ran pandoc --to="html" --output="test.html" --template="GitHub.html5" "test.md"`
so the `--mathjax` argument is not even considered. Same btw for `--katex`. 

I'm on Arch Linux | Pandoc 2.7.3 | recent vim-pandoc

**Comment by dpo** [comment]
I confirm that I have the same issue on macOS.
